apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdoc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdoc-server
  template:
    metadata:
      labels:
        app: sdoc-server
    spec:
      containers:
        - name: sdoc-server
          image: seafileltd/sdoc-server:1.0-latest
          ports:
            - containerPort: 8000
          env:
            # - name: SEAFILE_SERVER_HOSTNAME
            #   value: "seafile.example.com"  # Change to your Seafile hostname
            # - name: SEAFILE_SERVER_PROTOCOL
            #   value: "https"
            - name: LOG_LEVEL
              value: "info"
          volumeMounts:
            - mountPath: /opt/sdoc-server/data
              name: sdoc-server-storage
      volumes:
        - name: sdoc-server-storage
          persistentVolumeClaim:
            claimName: sdoc-server-pvc
