apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdoc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdoc-server
  template:
    metadata:
      labels:
        app: sdoc-server
    spec:
      containers:
        - name: sdoc-server
          image: seafileltd/sdoc-server:1.0-latest
          ports:
            - containerPort: 80
          env:
            # - name: SEAFILE_SERVER_PROTOCOL
            #   value: "https"
            # - name: SEAFILE_SERVER_HOSTNAME
            #   value: "seafile.local-cluster.dev"
            - name: SEAHUB_SERVICE_URL
              value: "https://seafile.local-cluster.dev"
            - name: JWT_PRIVATE_KEY
              value: "A3s85fwpaq2iipd5gY7TvwholJ23BedJDvfjfReu"  # Change this to a proper key
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "seafile" #db's password
            - name: DB_PASSWORD
              value: "db_dev" #db's password
            - name: DB_NAME
              value: "seahub_db" #db's password
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
          volumeMounts:
            - mountPath: /shared
              name: sdoc-server-storage
            - name: ca-pemstore
              mountPath: /usr/local/share/ca-certificates/sdoc-server.crt  # Path to mount the certificate
              subPath: my-cert.pem  # Reference the key from the ConfigMap
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "update-ca-certificates"]
      volumes:
        - name: ca-pemstore
          configMap:
            name: ca-pemstore  # Reference the ConfigMap
        - name: sdoc-server-storage
          persistentVolumeClaim:
            claimName: sdoc-server-storage
