apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-pemstore
  annotations:
    avp.kubernetes.io/path: "secret/data/tls/root-cert"
stringData:
  tls.crt: |
    <tls.crt>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:12.0-latest
          #image: docker.seadrive.org/seafileltd/seafile-pro-mc:11.0-latest
          env:
            - name: JWT_PRIVATE_KEY
              value: "A3s85fwpaq2iipd5gY7TvwholJ23BedJDvfjfReu"  # Change this to a proper key
            - name: DB_HOST
              value: "mariadb"
            - name: DB_USER
              value: "seafile" #db's password
            - name: DB_PASSWORD
              value: "db_dev" #db's password
            - name: DB_ROOT_PASSWD
              value: "db_dev" #db's password
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
            - name: INIT_SEAFILE_ADMIN_EMAIL
              value: "admin@seafile.com" #admin email
            - name: INIT_SEAFILE_ADMIN_PASSWORD
              value: "admin_password" #admin password
            - name: SEAFILE_SERVER_PROTOCOL
              value: "https"           
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "seafile.local-cluster.dev"
            - name: ENABLE_SEADOC
              value: "true"
            - name: SEADOC_SERVER_URL
              value: "https://seafile.local-cluster.dev/sdoc-server"

          ports:
            - containerPort: 80
            # - containerPort: 443
            #   name:  seafile-secure
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
            - name: ca-pemstore
              mountPath: /opt/seafile/seafile-server-12.0.9/seahub/thirdpart/certifi/cacert.pem  # Path to mount the certificate
              subPath: tls.crt  # Reference the key from the ConfigMap
      volumes:
        - name: ca-pemstore
          configMap:
            name: ca-pemstore  # Reference the ConfigMap
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
      # to get image from protected repository
      imagePullSecrets:
        - name: regcred

