apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:12.0-latest
          #image: docker.seadrive.org/seafileltd/seafile-pro-mc:11.0-latest
          env:
            - name: JWT_PRIVATE_KEY
              value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRE5VRFpsTGZQV2dyWFgKbHFlVXpmeWI2cExvSmY3eE8vbndrdG83ekswZCs2d25KdjhBNTNwYWtRaHNuQVVlUmV6S2hwUEFpMUJVM1UyaApldzNRQWJLSURoQnVpZUQrSStJclRUc3hBVGVhbjlvN3cxdExtM2FpVm9OY1pPOEVVTGRGOThhcTZubVdEYm42CjJqTHJFam16WmQxYXVKdGhBVDc0RkVlcW9kWUcyMkVLZWRBMkNpT0F5dmpKWE9MRldiVFNIRWFBOFQrVnZJMjMKNE9TamNrWWJNc1ZzMWhqN0czU3lMMzhmVkZJVUttaUx0U2V2U2tuVDMya1pocEExRWFuWSttQXc5S0pGbUYrMwpzRVRBRkJmamZYTiszTmg1ZmlvSllHbnZ2cU5CUUkxNU55aFl5Z2lBRnpsc25jQXR4VXBTZXpPeUFaR3hIeVNnCjIzdVZleHBUQWdNQkFBRUNnZ0VBS0FYY2JMSGVDREYzMER4Nms0dnFFOXpRNFhkU3NPVHZycUY1OEZGUVovbGgKRUVyT1IvZFh4eUxob1FaekN2azNsUzFSelNWN05lZmtFN2dBczgwNDU4UFNHVEpBalZvaVl5Mk5mZHFPWTlLSQpnTUR1NFppL01oc3FSVThadHQ0ak0veittZC9XYnRWakxVN3V3UnRPNnpWT3hyb1k4L3FCczJ1RW92TWtYVFo1CjhYUUthSUg4VHlYWDJZRWdvWkFpMkpCaUlKaTZldEJwaTg1Mkl0OVRwOTdHQTUzd0NxY1IrZTRMOUY3dU1LUk0KUFE1aFJzR0orc244UnFhYm5wUThBUWt6TUN3WmVadHZZSzRTS0E3WCtOdENPeVdURW5GVVZoRjR4eVYwS0NZUAorUDluN2NzNGFvdHJQMnZTUWtOZHIvRVpCVEx3RElhS1F4d1VsTVp1alFLQmdRRDhqVGhCUGJXM29QQWovRkNXCi9XaGM4NjU0NVdSTUZUb0FaeC9ZemI4UjNzb3YvREZvQzBBdUFOQmF6d084M2hKYUhUR2RaNk1GUEV3TDdXYXkKV2xCRzdDRDI4bWpoTTdaV2VJMlBjeTVYRUdIYlEzZTRNM3p2QUpsOWtkQURVaVIxSmNIRzJTU1dKQ21naWg1Qwp2ZUFWRmN5NnU0cjlEQ0c0Mks1MWpZRlFYd0tCZ1FEUUhkKzBOZG1DZ1V6LzlPVU81cE4zSW53T2ZnSEY5RGF0CitUeUdFbkp3aEhVMTBiWEgyK2YzeFpSeU9Ya3Q2WUh6a3IybERHVEdwUHRrU3hOM3JObTRxZlVIak1VWFNtN1kKajZhVmVoVitkcSt2dFhacUwwRFRwZ0IzYmtUTnVza0RlWkxyT201SmRKdlFtRGJsdnJ2Vyt3QUhoUWwwOGM0Zgo3d3NkWmhYcWpRS0JnUURFSWFnZWdwNHREWDl4Y3ZIalVNbEw1ck1Ja0oxanVOaGlsN1BUMjNVWG03M0pwa0Y0Clc4UnI5WlhaOEFzbkVnK09qRDJMMElCNkFHbk9tWCszNHd1VkNLeFJHOUQzbEFGM0JnaHA3emw5dytzN0xSbzgKb3ovVEhOUVhBTFphM2VBU1dsQXk3VS9NaWlrSjFEbkwrMG1iRm1MNFljMSsxMzBZNEs0Yi9Oa0FZUUtCZ0h1LwpsN28zWHV1TDZQWTFiMUpwNW51cmhLcTFZR2FOclVuTGJxS21LMmdlU3ZmQ2g5MmNOQldQWlpKNS9FVkJtT1QxCmQxREJ5dGFYV1dnc2dCbmtMTjN5S1dIZzRYelU1STVlOUlYalB3NmdraHpmd05hbzNGbzlWZit1RUxsbi9JalYKYkhmMG1ZbVNEZWg5NmY2NGFFY1BudGZaMG1LNE9ZR2hpVEZrOTFrdEFvR0FSS0trZC9VZHp5MzdTQWVRekVkQQo4VitzN3R0UTduY04yWW0vVmRLSFdMRWlRYm0rOGVueG05NVZRVERyLzZFS1lvbUJQVk9KREpvMGM1NzZ4WndmCmJIOHVMSnNRcFArL203ZHhsdnkzdW1iYWNyYUNTQUE2RW4vaS9ITExyQ2VyR1VRSm1md3hESWx0WjBhSlp1ZHkKbnJJdWpLUllGS0VORytiK2RPS2RjVXM9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"  # Change this to a proper key
            - name: DB_HOST
              value: "mariadb"
            - name: DB_USER
              value: "seafile" #db's password
            - name: DB_ROOT_PASSWD
              value: "db_dev" #db's password
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
            - name: INIT_SEAFILE_ADMIN_EMAIL
              value: "admin@seafile.com" #admin email
            - name: INIT_SEAFILE_ADMIN_PASSWORD
              value: "admin_password" #admin password
            - name: SEAFILE_SERVER_PROTOCOL
              value: "https"           
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "seafile.local-cluster.dev"
            - name: ENABLE_SEADOC
              value: "true"
            - name: SEADOC_SERVER_URL
              value: "https://sdoc-server.local-cluster.dev/sdoc-server"

          ports:
            - containerPort: 80
            # - containerPort: 443
            #   name:  seafile-secure
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
      # to get image from protected repository
      imagePullSecrets:
        - name: regcred

