apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          #        image: seafileltd/seafile-mc:9.0.10
          image: seafileltd/seafile-mc:11.0-latest
          #image: docker.seadrive.org/seafileltd/seafile-pro-mc:11.0-latest
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_ROOT_PASSWD
              value: "db_dev" #db's password
            - name: TIME_ZONE
              value: "Europe/Amsterdam"
            - name: SEAFILE_ADMIN_EMAIL
              value: "admin@seafile.com" #admin email
            - name: SEAFILE_ADMIN_PASSWORD
              value: "admin_password" #admin password
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://seafile.local-cluster.dev"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "seafile.local-cluster.dev"
          ports:
            - containerPort: 80
            # - containerPort: 443
            #   name:  seafile-secure
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
      # to get image from protected repository
      imagePullSecrets:
        - name: regcred

